name: 'Setup OKD OpenShift Cluster'
description: 'This action sets up an OKD OpenShift Cluster in your environment'
author: 'Marc Nuri'
branding:
  icon: circle
  color: red
inputs:
  oc version:
    description: 'Version of OKD OpenShift to deploy'
    required: true
  github token:
    description: 'GITHUB_TOKEN to be able to perform requests to GH REST API (with no limit)'
runs:
  using: 'node12'
  main: 'src/index.js'
